---
title: "Legewie - Analysis of Interests"
output: html_document
---
#Analysis 
```{r}
# working directory
PATH <- "/n/legewie_lab/Lab/neighborhood-boundaries/replication-material"
## load libraries
library("MASS")
library("tidyverse")
library("stargazer")
library("glue")
library("spdplyr")
library("BoundaryDetection")
library("multiwayvcov")
library("lmtest")
library("car", pos = length(search()))
library("colourschemes")
library("scales")
library("Hmisc")
library("rgeos")
library("maptools")

install.packages("BoundaryDetection")

# utility functions
source(file.path(PATH, "00-utils.r"))
scale_color_cts <- function(domain, x = NULL, colors = c("#F1EEF6", "#034E7B"), n = 9) {
    if(is.null(x) & is.null(domain)) stop("Set either 'x' or 'domain'")
    palette   <- colorRampPalette(colors)(n)
    values <- seq(domain[1], domain[2], length.out = n)
    scale  <- colourschemes::nearestScheme(data.frame(col = palette, values = values))
    f      <- function(x, mis = "#f6f6f6") {
        col <- rep(mis, length(x))
        col[!is.na(x)] <- scale(x[!is.na(x)])
        return(col)
    }
    return(f)
}
scale_color <- scale_color_cts(domain = c(0,1), n = 9)
fit_glmnb <- function(d, formula, cluster) {
    m <- glm.nb(formula, data = d[sel_chi,])
    vcov_cluster <- cluster.vcov(m, cluster = cluster)
    coeftest(m, vcov_cluster)
}
mi_combine <- function(m, df) {
    k       <- length(m)
    out     <- m[[1]]
    out[,1] <- m %>% map(~.x[,1]) %>% {do.call(cbind, .)} %>% rowMeans()
    wvar    <- m %>% map(~.x[,2]) %>% {do.call(cbind, .)} %>% apply(1, function(x) mean(x^2))
    bvar    <- m %>% map(~.x[,1]) %>% {do.call(cbind, .)} %>% apply(1, function(x) var(x))
    out[,2] <- sqrt(wvar + (1 + 1/k) * bvar)
    out[,3] <-  out[,1] / out[,2]
    out[,4] <-  2 * pt(-abs(out[,3]), df = df)
    out
}

# read data
ccahs  <- read_rds(file.path(PATH, "data", "ccahs-2001-2003-recoded.rds"))
ccahs  <- ccahs %>% mutate(cb_code = str_c(state, county, tract, block), bg_code = str_sub(cb_code, 1, 12))
chi_cb <- read_rds(file.path(PATH, "data", "census-cook-cb-2010.rds"))
chi_cb <- chi_cb@data %>%
    filter(chicago) %>%
    mutate(
        cb_code                  = paste0(state, county, tract, block),
        bg_code                  = paste0(state, county, tract, block_group),
        ct_code                  = paste0(state, county, tract),
        crime_violent_2001_rate  = crime_violent_2001/pop,
        crime_property_2001_rate = crime_property_2001/pop,
        crime_violent_2006_rate  = crime_violent_2006/pop,
        crime_property_2006_rate = crime_property_2006/pop,
        crime_violent_2010_rate  = crime_violent_2010/pop,
        crime_property_2010_rate = crime_property_2010/pop,
        major_road               = roads_primary | roads_secondary
    )
chi_cb_pv <- read_rds(file.path(PATH, "data", "census-cook-cb-plausible-values.rds"))
# chi_cb_pv <- chi_cb_pv %>% map(~ .x %>% mutate(major_road = roads_primary | roads_secondary))

## Tab 1: Correlation matrix
corstarsl <- function(x) {
    require(Hmisc)
    x <- as.matrix(x)
    R <- Hmisc::rcorr(x)$r
    p <- Hmisc::rcorr(x)$P
    # define notions for significance levels; spacing is important.
    mystars <- ifelse(p < .001, "***", ifelse(p < .01, "** ", ifelse(p < .05, "* ", " ")))
    # trunctuate the matrix that holds the correlations to two decimal
    R <- format(round(cbind(rep(-1.11, ncol(x)), R), 2))[,-1]
    # build a new matrix that includes the correlations with their apropriate stars
    Rnew <- matrix(paste(R, mystars, sep=""), ncol=ncol(x))
    diag(Rnew) <- paste(diag(R), " ", sep="")
    rownames(Rnew) <- colnames(x)
    colnames(Rnew) <- paste(colnames(x), "", sep="")
    # remove upper triangle
    Rnew <- as.matrix(Rnew)
    Rnew[upper.tri(Rnew, diag = TRUE)] <- ""
    Rnew <- as.data.frame(Rnew)
    # remove last column and return the matrix (which is now a data frame)
    Rnew <- cbind(Rnew[1:length(Rnew)-1])
    return(Rnew)
}

sel_chi  <- with(chi_cb, pop !=0 & hh != 0 & !park_area & !is.infinite(edge_race_areal) & !is.infinite(p_race_white_blv) & !is.infinite(p_race_black_blv) & !is.infinite(p_race_hisp_blv))
COR      <- corstarsl(with(chi_cb[sel_chi,], cbind(p_race_white, p_race_black, p_race_hisp, p_white_splag, p_black_splag, p_hisp_splag, p_race_white_blv, p_race_black_blv, p_race_hisp_blv, edge_race_areal)))
COR$Mean <- round(apply(chi_cb[sel_chi,rownames(COR)], 2, mean, na.rm = TRUE), 2)
COR$SD   <- round(apply(chi_cb[sel_chi,rownames(COR)], 2, sd, na.rm = TRUE), 2)
COR      <- select(COR, Mean, SD, everything())
rownames(COR) <- c("1. Prop. White", "2. Prop. Black", "3. Prop. Hispanic", "4. Prop. White (spatial lag)", "5. Prop. Black (spatial lag)", "6. Prop. Hispanic (spatial lag)", "7. NBHD Boundary (White)", "8. NBHD Boundary (Black)", "9. NBHD Boundary (Hispanic)", "10. NBHD Boundary (combined)")
names(COR)[-(1:2)] <- 1:(ncol(COR) - 2)
# correlation table
stargazer(COR, digits = 2, initial.zero = TRUE, summary = FALSE, type = "text")

## Tab A2: Correlation matrix
COR      <- corstarsl(with(chi_cb[sel_chi,], cbind(p_race_white_blv, p_race_black_blv, p_race_hisp_blv, edge_race_areal, major_road, touches_park, river, elementary_school_district)))
COR$Mean <- round(apply(chi_cb[sel_chi,rownames(COR)], 2, mean, na.rm = TRUE), 2)
COR$SD   <- round(apply(chi_cb[sel_chi,rownames(COR)], 2, sd, na.rm = TRUE), 2)
COR      <- select(COR, Mean, SD, everything())
rownames(COR) <- c("1. NBHD Boundary (White)", "2. NBHD Boundary (Black)", "3. NBHD Boundary (Hispanic)", "4. NBHD Boundary (combined)", "5. Adjacent to Major Road", "6. Adjacent to Park", "7. Adjacent to River", "8. Elem. School District Border")
names(COR)[-(1:2)] <- 1:(ncol(COR) - 2)
# correlation table
stargazer(COR, digits = 2, initial.zero = TRUE, summary = FALSE, type = "text")

## Tab 2: Neighborhood boundaries and violent crime
sel_chi <- with(chi_cb, pop !=0 & hh != 0 & !park_area & !is.infinite(edge_race_areal))
U     <- "log(pop) + crime_violent_2001_rate + crime_property_2001_rate + std(p_race_black) + std(p_race_hisp) + std(p_race_asian) + std(con_disadv_bg) + std(res_instab_bg) + std(immi_con_bg) + std(hhi) + std(age_15_35_male)"
U     <- "I(pop/100) + crime_violent_2001 + crime_property_2001 + std(p_race_black) + std(p_race_hisp) + std(p_race_asian) + std(con_disadv_bg) + std(res_instab_bg) + std(immi_con_bg) + std(hhi) + std(age_15_35_male)"
SPLAG <- "std(p_black_splag) + std(p_hisp_splag) + std(p_asian_splag) + std(hhi_splag)"
f <- list(
        "crime_violent_2011 ~ {U}",
        "crime_violent_2011 ~ {U} + std(edge_race_areal)",
        "crime_violent_2011 ~ {U} + std(edge_race_areal) + major_road + touches_park + river + elementary_school_district",
        "crime_violent_2011 ~ {U} + std(edge_race_areal) + major_road + touches_park + river + elementary_school_district + {SPLAG}"
    ) %>%
    map(glue) %>%
    map(as.formula)
# fit negative bin models
m <- map(f, ~glm.nb(.x, data = chi_cb[sel_chi,]))
# clustered standard errors
cluster      <- chi_cb$bg_code[sel_chi]
vcov_cluster <- map(m, cluster.vcov, cluster = cluster)
m_cluster    <- map2(m, vcov_cluster, coeftest)
# regression table
stargazer(m, type = "text")
stargazer(m_cluster, type = "text")
# Multi-collinearity
fit <- lm(f[[3]], data = chi_cb[sel_chi,])
vif(fit)
fit <- lm(f[[4]], data = chi_cb[sel_chi,])
vif(fit)
# plausible values
m1 <- chi_cb_pv %>%
    map(fit_glmnb, formula = f[[1]], cluster = cluster) %>%
    mi_combine(df = m[[1]]$df.residual)
m2 <- chi_cb_pv %>%
    map(fit_glmnb, formula = f[[2]], cluster = cluster) %>%
    mi_combine(df = m[[1]]$df.residual)
m3 <- chi_cb_pv %>%
    map(fit_glmnb, formula = f[[3]], cluster = cluster) %>%
    mi_combine(df = m[[1]]$df.residual)
m4 <- chi_cb_pv %>%
    map(fit_glmnb, formula = f[[4]], cluster = cluster) %>%
    mi_combine(df = m[[1]]$df.residual)
stargazer(m1, m2, m3, m4, type = "text")

## Tab 3: Supplementary analysis: Neighborhood boundaries and violent crime
f1 <- crime_violent_2011 ~ I(pop/100) + crime_violent_2001 + crime_property_2001 + 
    std(p_race_black) + std(p_race_hisp) + std(p_race_asian) + 
    std(con_disadv_bg) + std(res_instab_bg) + std(immi_con_bg) + 
    std(hhi) + std(age_15_35_male) + std(edge_race_wb) + std(edge_race_wh) + std(edge_race_bh) + major_road + 
    touches_park + river + elementary_school_district + std(p_black_splag) + 
    std(p_hisp_splag) + std(p_asian_splag) + std(hhi_splag)
f2 <- crime_violent_2011 ~ offset(log(pop/100)) + crime_violent_2001_rate + crime_property_2001_rate + 
    std(p_race_black) + std(p_race_hisp) + std(p_race_asian) + 
    std(con_disadv_bg) + std(res_instab_bg) + std(immi_con_bg) + 
    std(hhi) + std(age_15_35_male) + std(edge_race_areal) + major_road + 
    touches_park + river + elementary_school_district + std(p_black_splag) + 
    std(p_hisp_splag) + std(p_asian_splag) + std(hhi_splag)
f3 <- crime_violent_day_2011 ~ I(pop/100) + crime_violent_2001 + crime_property_2001 + 
    std(p_race_black) + std(p_race_hisp) + std(p_race_asian) + 
    std(con_disadv_bg) + std(res_instab_bg) + std(immi_con_bg) + 
    std(hhi) + std(age_15_35_male) + std(edge_race_areal) + major_road + 
    touches_park + river + elementary_school_district + std(p_black_splag) + 
    std(p_hisp_splag) + std(p_asian_splag) + std(hhi_splag)
f4 <- crime_violent_night_2011 ~ I(pop/100) + crime_violent_2001 + crime_property_2001 + 
    std(p_race_black) + std(p_race_hisp) + std(p_race_asian) + 
    std(con_disadv_bg) + std(res_instab_bg) + std(immi_con_bg) + 
    std(hhi) + std(age_15_35_male) + std(edge_race_areal) + major_road + 
    touches_park + river + elementary_school_district + std(p_black_splag) + 
    std(p_hisp_splag) + std(p_asian_splag) + std(hhi_splag)
f5 <- crime_violent_2011_2016 ~ I(pop/100) + crime_violent_2001 + crime_property_2001 + 
    std(p_race_black) + std(p_race_hisp) + std(p_race_asian) + 
    std(con_disadv_bg) + std(res_instab_bg) + std(immi_con_bg) + 
    std(hhi) + std(age_15_35_male) + std(edge_race_areal) + major_road + 
    touches_park + river + elementary_school_district + std(p_black_splag) + 
    std(p_hisp_splag) + std(p_asian_splag) + std(hhi_splag)
m1 <- chi_cb_pv %>%
    map(fit_glmnb, formula = f1, cluster = cluster) %>%
    mi_combine(df = m[[1]]$df.residual)
m2 <- chi_cb_pv %>%
    map(fit_glmnb, formula = f2, cluster = cluster) %>%
    mi_combine(df = m[[1]]$df.residual)
m3 <- chi_cb_pv %>%
    map(fit_glmnb, formula = f3, cluster = cluster) %>%
    mi_combine(df = m[[1]]$df.residual)
m4 <- chi_cb_pv %>%
    map(fit_glmnb, formula = f4, cluster = cluster) %>%
    mi_combine(df = m[[1]]$df.residual)
m5 <- chi_cb_pv %>%
    map(fit_glmnb, formula = f5, cluster = cluster) %>%
    mi_combine(df = m[[1]]$df.residual)
# regression table
stargazer(m2, m3, m4, m5, m1, type = "text")


## Tab 4: Neighborhood boundaries, violent crimes, perceived violence and homicides

# model 1: violent crime (model 3 from tab 1)
f <- crime_violent_2011 ~ I(pop/100) + crime_violent_2001 + crime_property_2001 + 
    std(p_race_black) + std(p_race_hisp) + std(p_race_asian) + 
    std(con_disadv_bg) + std(res_instab_bg) + std(immi_con_bg) + 
    std(hhi) + std(age_15_35_male) + std(edge_race_areal) + major_road + 
    touches_park + river + elementary_school_district + std(p_black_splag) + 
    std(p_hisp_splag) + std(p_asian_splag) + std(hhi_splag)
m4 <- chi_cb_pv %>%
    map(fit_glmnb, formula = f, cluster = cluster) %>%
    mi_combine(df = m[[1]]$df.residual)
# model 2: Homicides
f <- crime_homicide_night_2011 ~ I(pop/100) + crime_violent_2001 + crime_property_2001 + 
    std(p_race_black) + std(p_race_hisp) + std(p_race_asian) + 
    std(con_disadv_bg) + std(res_instab_bg) + std(immi_con_bg) + 
    std(hhi) + std(age_15_35_male) + std(edge_race_areal) + major_road + 
    touches_park + river + elementary_school_district + std(p_black_splag) + 
    std(p_hisp_splag) + std(p_asian_splag) + std(hhi_splag)
m2 <- chi_cb_pv %>%
    map(fit_glmnb, formula = f, cluster = cluster) %>%
    mi_combine(df = m[[1]]$df.residual)
# model 3: perceived violence
sel_ccahs <- with(ccahs, pop !=0 & hh != 0 & !is.infinite(edge_race_areal) & race != 5 &
    complete.cases(violence_perceived_scale, female, edu_years, emp_status, race, age, home_ownership, foreign_born, edge_race_areal))
f <- std(violence_perceived_scale) ~ female + std(edu_years) + factor(emp_status) + factor(race) +
    std(age) + home_ownership + foreign_born +
    log(pop) + std(p_race_black) + std(p_race_hisp) + std(p_race_asian) +
    std(con_disadv_ct) + std(res_instab_ct) + std(immi_con_ct) + 
    std(hhi) + std(age_15_35_male) + std(edge_race_areal) + std(p_black_splag) + 
    std(p_hisp_splag) + std(p_asian_splag) + std(hhi_splag)
f <- std(violence_perceived_scale) ~ female + std(edu_years) + factor(emp_status) + factor(race) +
    std(age) + home_ownership + foreign_born +
    log(pop) + std(p_race_black) + std(p_race_hisp) + std(p_race_asian) +
    std(con_disadv_bg) + std(res_instab_bg) + std(immi_con_bg) + 
    std(hhi) + std(age_15_35_male) + std(edge_race_areal) + std(p_black_splag) + 
    std(p_hisp_splag) + std(p_asian_splag) + std(hhi_splag)
m3         <- lm(f, data = ccahs[sel_ccahs,])
vcov_m3    <- cluster.vcov(m3, cluster = ccahs$bg_code[sel_ccahs])
m3_cluster <- coeftest(m3, vcov_m3)

# regression table
stargazer(m4, m2, m3, type = "text", keep = c("edge_.*"), keep.stat = "n", dep.var.labels.include = FALSE)


## Figure 1
chi_bg <- read_rds(file.path(PATH, "data", "census-cook-bg-2010.rds")) %>% filter(chicago)
# exclude O'Hare International Airport (tract `17031980000` and `17031770602`)
sel_airport <- chi_bg$tract %in% c("980000", "770602")
sel_airport <- sel_airport | rgeos::gTouches(rgeos::gUnaryUnion(chi_bg[sel_airport,]), chi_bg, byid = TRUE)[,1]
chi_bg      <- chi_bg[!sel_airport,]
# chicago line file
sl_bg  <- areal_wombling(chi_bg, c("p_race_white", "p_race_black", "p_race_hisp", "p_race_asian", "hhinc_average"))
chi    <- unionSpatialPolygons(chi_bg, IDs = rep(1, length(chi_bg)))

png(file.path(PATH, "chi-bg-01-choropleth.png"), width=3.05, height=4.5, units="in", res=600)
par(mfrow=c(1,1), mar=c(0,0,0,0), cex=0.8, cex.lab=0.8, cex.main=0.8, mgp=c(1.2,0.15,0), cex.axis=0.7, tck=-0.01)
plot(chi_bg, lwd = 0.1, col = scale_color(chi_bg$p_race_black), bor = "white")
# plot(chi, lwd = 0.5)
vals <- quantile(chi_bg$p_race_black, probs = c(0, 0.25, .5, 0.75, 1), na.rm = TRUE) 
legend(-87.87, 41.73, legend = c("0%", "25%","50%", "75%", "100%"), fill = scale_color(vals), cex = 0.8,
    box.lty = 0, border = "#00000000", title = "Percent Black", title.adj = 3.5)
dev.off()
png(file.path(PATH, "chi-bg-02-borders.png"), width=3.05, height=4.5, units="in", res=600)
par(mfrow=c(1,1), mar=c(0,0,0,0), cex=0.8, cex.lab=0.8, cex.main=0.8, mgp=c(1.2,0.15,0), cex.axis=0.7, tck=-0.01)
plot(sl_bg, lwd = rescale(sl_bg$p_race_black_blv, to = c(0.1, 1.25)))
plot(chi, lwd = 0.5, add = TRUE)
legend(-87.87, 41.73, legend = c("0.0", "0.25", "0.5", "0.75", "1.0"), lwd = rescale(c(0, 0.25, 0.5, 0.75, 1), to = c(0.1, 1.25)),
    cex = 0.8, box.lty = 0, border = "#00000000", title = "Boundary Value", title.adj = 3.5)
dev.off()
png(file.path(PATH, "chi-bg-03-border-areas.png"), width=3.05, height=4.5, units="in", res=600)
par(mfrow=c(1,1), mar=c(0,0,0,0), cex=0.8, cex.lab=0.8, cex.main=0.8, mgp=c(1.2,0.15,0), cex.axis=0.7, tck=-0.01)
plot(chi_bg, lwd = 0.1, col = scale_color(chi_bg$p_race_black_blv), bor = "white")
legend(-87.87, 41.73, legend = c("0.0", "0.25", "0.5", "0.75", "1.0"), fill = scale_color(c(0, 0.25, 0.5, 0.75, 1)),
    cex = 0.8, box.lty = 0, border = "#00000000", title = "Boundary Value", title.adj = 3.5)
dev.off()
```

#Physical Boundaries
```{r}
# working directory
PATH <- "/n/legewie_lab/Lab/neighborhood-boundaries/replication-material"
## load libraries
library("MASS")
library("tidyverse")
library("readr")
library("stargazer")
library("spdep")
library("purrr")
library("MASS")
library("spdplyr")
library("rgeos")
library("BoundaryDetection")
library("maptools")
library("car", pos = length(search()))
# utility functions
proj4  <- CRS(" +proj=lcc +lat_1=40.66666666666666 +lat_2=41.03333333333333 +lat_0=40.16666666666666 +lon_0=-74 +x_0=300000 +y_0=0 +datum=NAD83 +units=us-ft +no_defs +ellps=GRS80 +towgs84=0,0,0")
source(file.path(PATH, "00-utils.r"))
# read data
chi_cb <- read_rds(file.path(PATH, "data", "census-cook-cb-2010.rds"))
chi_cb <- chi_cb %>%
    filter(chicago) %>%
    spTransform(proj4) %>%
    mutate(
        rowid   = row.names(.),
        cb_code = paste0(state, county, tract, block),
        bg_code = paste0(state, county, tract, block_group)
    )
chi_cb <- chi_cb[-28816,]

## Parks
chi_parks <- rgdal::readOGR(path.expand(file.path(PATH, "data", "shapefiles", "chicago-parks-2012")), "Parks_Aug2012")
chi_parks <- chi_parks %>% spTransform(proj4) %>% unionSpatialPolygons(IDs = rep(1, length(chi_parks)))
# plot(chi_parks, col = "#90c09050", bor = "#ffffff00")
# Difference between census blocks and parks
cb_parks_diff <- rgeos::gDifference(chi_cb, chi_parks, byid = TRUE)
row.names(cb_parks_diff) <- row.names(cb_parks_diff) %>% str_replace(" 1", "")
cb_parks_area <- tibble(
        rowid        = row.names(cb_parks_diff),
        area_notpark = gArea(cb_parks_diff, byid = TRUE),
    ) 
chi_cb@data <- chi_cb@data %>%
    left_join(cb_parks_area, by = "rowid") %>%
    mutate(
        area         = gArea(chi_cb, byid = TRUE) %>% unname(),
        area_notpark = coalesce(area_notpark, area),
        p_park       = (area - area_notpark)/area,
        park_area    = p_park > 0.5,
    )
# Adjacent to park
chi_cb_parks <- chi_cb %>%
    filter(park_area) %>%
    select(state, county, tract, block, cb_code, p_park) %>%
    unionSpatialPolygons(IDs = rep(1, length(.)))
chi_cb$touches_park <- rgeos::gTouches(chi_cb, chi_cb_parks, byid = TRUE)[1,]

## Topological Faces (Polygons with All Geocodes)
# Download: ftp://ftp2.census.gov/geo/tiger/TIGER2010/FACES/tl_2010_17031_faces.zip
# Documentation: http://www2.census.gov/geo/pdfs/maps-data/data/tiger/tgrshp2010/TGRSHP10SF1.pdf (Section 5.20)
chi_faces <- rgdal::readOGR(path.expand(file.path(PATH, "data", "shapefiles", "chicago-faces-2010")), "tl_2010_17031_faces")
chi_faces <- chi_faces@data %>%
    transmute(
        id_face     = TFID,
        state       = STATEFP10,
        county      = COUNTYFP10,
        tract       = TRACTCE10,
        block_group = BLKGRPCE10,
        block       = BLOCKCE10,
        schooldist_elementary = ELSDLEA10,
        schooldist_secondary  = SCSDLEA10,
        schooldist_unified    = UNSDLEA10
    ) %>%
    mutate_if(is.factor, as.character) %>%
    as_tibble()

## Linear Features
# Download: https://www.census.gov/geo/maps-data/data/tiger-line.html
# Documentation: http://www2.census.gov/geo/pdfs/maps-data/data/tiger/tgrshp2010/TGRSHP10SF1.pdf (Section 5.11)
chi_lines <- rgdal::readOGR(path.expand(file.path(PATH, "data", "shapefiles", "chicago-lines-2010")), "tl_2010_17031_edges")
chi_lines <- chi_lines %>% transmute(id_edge = TLID, id_face_left = TFIDL, id_face_right = TFIDR, fullname = FULLNAME, MTFCC = MTFCC)
# join lines with geo-codes of left and right faces 
chi_lines <- chi_lines %>%
    left_join(chi_faces, by = c('id_face_left' = 'id_face')) %>%
    left_join(select(chi_faces, -state, -county), by = c('id_face_right' = 'id_face'), suffix = c("_left", "_right")) %>%
    mutate(
        cb_code_left = str_c(state, county, tract_left, block_left),
        cb_code_right = str_c(state, county, tract_right, block_right)
    ) %>%
    select(-state, -county, -tract_left, -block_group_left, -block_left, -tract_right, -block_group_right, -block_right)

## Primary and Secondary roads (Highways)
# Primary roads (MTFCC = "S1100") are generally divided, limited-access highways within the Federal interstate highway system or under state management, and are distinguished by the presence of interchanges. These highways are accessible by ramps and may include some toll highways.
# Secondary roads (MTFCC = "S1200") are main arteries, usually in the U.S. Highway, State Highway or County Highway system. These roads have one or more lanes of traffic in each direction, may or may not be divided, and usually have at-grade intersections with many other roads and driveways. They often have both a local name and a route number.
chi_roads <- chi_lines %>% filter(MTFCC %in% c("S1100", "S1200"))
# census block codes for primary and secondary roads
chi_roads_primary <- chi_roads@data %>%
    filter(MTFCC == "S1100") %>%
    select(id_edge, cb_code_left, cb_code_right) %>%
    tidyr::gather(side, cb_code, cb_code_left, cb_code_right) %>%
    pull("cb_code") %>%
    unique() %>%
    na.omit()
chi_roads_secondary <- chi_roads@data %>%
    filter(MTFCC == "S1200") %>%
    select(id_edge, cb_code_left, cb_code_right) %>%
    tidyr::gather(side, cb_code, cb_code_left, cb_code_right) %>%
    pull("cb_code") %>%
    unique() %>%
    na.omit()
# add covariates to census block file
chi_cb <- chi_cb %>%
    mutate(
        roads_primary   = cb_code %in% chi_roads_primary,
        roads_secondary = cb_code %in% chi_roads_secondary,
    )

## Rivers
# Stream/River (MTFCC = "H3010") A natural flowing waterway. [includes anabranch, awawa, branch, brook, creek, distributary, fork, kill, pup, rio, and run]
chi_rivers <- chi_lines %>% filter(MTFCC %in% c("H3010"))
# census block codes for primary and secondary roads
chi_rivers_cb <- chi_rivers@data %>%
    select(id_edge, cb_code_left, cb_code_right) %>%
    tidyr::gather(side, cb_code, cb_code_left, cb_code_right) %>%
    pull("cb_code") %>%
    unique() %>%
    na.omit()
# add covariates to census block file
chi_cb <- chi_cb %>% mutate(river = cb_code %in% chi_rivers_cb)

## Distance to cps elementary school district
chi_cps_elementary <- rgdal::readOGR(path.expand(file.path(PATH, "data", "shapefiles", "cps-elementary-school-boundaries")), "cps-elementary-school-boundaries")
# school district: project and convert to spatial lines
chi_cps_elementary <- chi_cps_elementary %>% spTransform(proj4) %>% border_lines()
# census blocks: convert to spatial lines
chi_cb_sl       <- border_lines(chi_cb)
# school district: select valid spatial lines
sel_elementary <- (1:nrow(chi_cps_elementary) %>% map_dbl(~possibly(gDistance, otherwise = -9999)(chi_cb_sl[1,], chi_cps_elementary[.x,], byid = TRUE)[1])) != -9999
# census blocks: select valid spatial lines
sel_cb_sl <- 1:nrow(chi_cb_sl) %>%
    map(~possibly(gDistance, otherwise = NULL)(chi_cb_sl[.x,], chi_cps_elementary[sel_elementary,], byid = TRUE)) %>%
    map_lgl(is.matrix)
write_rds(sel_cb_sl, file.path(PATH, "data", "select-cb-sl-cps-elementary.rds"), compress = "gz")
# sel_cb_sl <- read_rds(file.path(PATH, "data", "select-cb-sl-cps-elementary.rds"))

# distance between census blocks and school district
dist_cb_cps_elementary <- rgeos::gDistance(chi_cb_sl[sel_cb_sl,], chi_cps_elementary[sel_elementary,], byid = TRUE)
write_rds(dist_cb_cps_elementary, file.path(PATH, "data", "dist-cb-cps-elementary.rds"), compress = "gz")
# dist_cb_cps_elementary <- read_rds(file.path(PATH, "data", "dist-cb-cps-elementary.rds"))
dist_cb_cps_elementary <- dist_cb_cps_elementary %>% apply(2, min)
# aggregate distance to census block level
chi_cb_sl_dist <- tibble(
        idx = names(dist_cb_cps_elementary),
        dist = unname(dist_cb_cps_elementary)
    ) %>%
    separate(idx, into = c("i", "j"), sep = "_") %>%
    mutate(
        i = str_replace(i, "i", "") %>% as.integer(),
        j = str_replace(j, "j", "") %>% as.integer(),
    )
dist_cps_elementary <- bind_rows(
        chi_cb_sl_dist %>% group_by(i) %>% summarize(dist = min(dist)),
        chi_cb_sl_dist %>% group_by(j) %>% summarize(dist = min(dist)) %>% rename(i = j)
    ) %>%
    group_by(i) %>%
    summarize(dist = min(dist))
write_rds(dist_cps_elementary, file.path(PATH, "data", "dist-cb-cps-elementary-reduced.rds"), compress = "gz")
dist_cps_elementary <- read_rds(file.path(PATH, "data", "dist-cb-cps-elementary-reduced.rds"))
# join distance with census block file
chi_cb@data <- chi_cb@data %>%
    mutate(i = 1:nrow(.)) %>%
    left_join(dist_cps_elementary) %>%
    rename(dist_cps_elementary = dist) %>%
    mutate(elementary_school_district = dist_cps_elementary %in% 0)

## save census data
write_rds(chi_cb, file.path(PATH, "data", "census-cook-cb-2010.rds"), compress = "gz")

## quit...
q(save = "no")
```

```{r}

```

```{r}

```



